export const playList = [
  {
    title: "Ambient",
    id: 142276242,
    url: "./Music/Ambient.mp3",
    author: "Stan Kraus",
    author_link: "https://soundcloud.com/stan-kraus",
  },
  {
    title: "Lo-Fi",
    id: 508749267,
    url: "./Music/music.mp3",
    author: "Epigenesis",
    author_link: "https://soundcloud.com/epigenes1s",
  },
  {
    title: "Work & Study",
    id: 751456812,
    url: "https://soundcloud.com/knightvibes/sets/calm-study-lofi-hiphop-beats",
    author: "Knight Vibes",
    author_link: "https://soundcloud.com/knightvibes",
  },
  {
    title: "Deep Focus",
    id: 1012023622,
    url: "https://soundcloud.com/lofi-mixes/sets/lofi-beats-to-sleep-to",
    author: "Lofi Mixes",
    author_link: "https://soundcloud.com/lofi-mixes",
  },
  {
    title: "Chillstep",
    id: 179820626,
    url: "https://soundcloud.com/zodiaclegends/sets/chillstep",
    author: "ZodiacLegends",
    author_link: "https://soundcloud.com/zodiaclegends",
  },
  {
    title: "Easy Listening",
    id: 267243161,
    url: "https://soundcloud.com/ferzrrn/sets/chillout-room-top-500",
    author: "ferzrrn",
    author_link: "https://soundcloud.com/ferzrrn",
  },
  {
    title: "Feel Good Vibes",
    id: 1661070083,
    url: "https://soundcloud.com/settingsailrecords/sets/morning-chill-morning-vibes",
    author: "Setting Sail Records",
    author_link: "https://soundcloud.com/settingsailrecords",
  },
  {
    title: "Future Chillout",
    id: 778631742,
    url: "https://soundcloud.com/sgyawriter/sets/chillout",
    author: "Sarah Y",
    author_link: "https://soundcloud.com/sgyawriter",
  },
  {
    title: "Future Garage",
    id: 272254392,
    url: "https://soundcloud.com/ferzrrn/sets/future-garage",
    author: "ferzrrn",
    author_link: "https://soundcloud.com/ferzrrn",
  },
  {
    title: "Future Bass",
    id: 315321832,
    url: "https://soundcloud.com/user-227164845/sets/future-bass",
    author: "PITYPARTY",
    author_link: "https://soundcloud.com/user-227164845",
  },
  {
    title: "Chillhop",
    id: 238833302,
    url: "https://soundcloud.com/charles-spinosa/sets/chill-beats",
    author: "Charles Spinosa",
    author_link: "https://soundcloud.com/charles-spinosa",
  },
  {
    title: "Trap",
    id: 380173691,
    url: "https://soundcloud.com/mczg/sets/brass-trap",
    author: "MCZG",
    author_link: "https://soundcloud.com/mczg",
  },
  {
    title: "Chill Trap",
    id: 380859764,
    url: "https://soundcloud.com/t_he_end/sets/chill-trap",
    author: "TH3 3ND",
    author_link: "https://soundcloud.com/t_he_end",
  },
  {
    title: "Lo-Fi Trap",
    id: 521891382,
    url: "https://soundcloud.com/gosmuckyourself/sets/lo-fi-trap",
    author: "smuck",
    author_link: "https://soundcloud.com/gosmuckyourself",
  },
  {
    title: "Jazz Trap",
    id: 1359634711,
    url: "https://soundcloud.com/direraptor22/sets/trapjazz",
    author: "DireRaptor22",
    author_link: "https://soundcloud.com/direraptor22",
  },
  {
    title: "Melodic Trap",
    id: 994059076,
    url: "https://soundcloud.com/user-227164845/sets/lovey-dovey",
    author: "PITYPARTY",
    author_link: "https://soundcloud.com/user-227164845",
  },
  {
    title: "Wave Trap",
    id: 995779555,
    url: "https://soundcloud.com/bleezzzy/sets/chill-trap-4",
    author: "BLEEZZZY",
    author_link: "https://soundcloud.com/bleezzzy",
  },
  {
    title: "Dark Trap",
    id: 862980522,
    url: "https://soundcloud.com/elvispalace/sets/dark-trap",
    author: "Elvis.",
    author_link: "https://soundcloud.com/elvispalace",
  },
  {
    title: "Dubstep",
    id: 268841855,
    url: "https://soundcloud.com/ferzrrn/sets/dubstep",
    author: "ferzrrn",
    author_link: "https://soundcloud.com/ferzrrn",
  },
  {
    title: "Melodic Dubstep",
    id: 241391477,
    url: "https://soundcloud.com/alecfalzone/sets/melodic-dubstep",
    author: "Alec Falzone",
    author_link: "https://soundcloud.com/alecfalzone",
  },
  {
    title: "Liquid Dubstep",
    id: 18718386,
    url: "https://soundcloud.com/officialjmt/sets/liquid-dubstep",
    author: "OfficialJMT",
    author_link: "https://soundcloud.com/officialjmt",
  },
  {
    title: "Deep Dubstep",
    id: 287925656,
    url: "https://soundcloud.com/vault-sounds-chiggs/sets/deep-dark-dubstep-grime-1",
    author: "CHGS140",
    author_link: "https://soundcloud.com/vault-sounds-chiggs",
  },
  {
    title: "Dark Dubstep",
    id: 624432006,
    url: "https://soundcloud.com/lost-coast-3/sets/forget",
    author: "Lost Coast",
    author_link: "https://soundcloud.com/lost-coast-3",
  },
  {
    title: "Heavy Dubstep",
    id: 141897717,
    url: "https://soundcloud.com/clifcon/sets/the-heaviest-of-the-heavy",
    author: "Clifcon",
    author_link: "https://soundcloud.com/clifcon",
  },
  {
    title: "Drum & Bass",
    id: 313874557,
    url: "https://soundcloud.com/ben-edgar-3/sets/dnb-liquid-dnb",
    author: "Ben Edgar",
    author_link: "https://soundcloud.com/ben-edgar-3",
  },
  {
    title: "Melodic Drum & Bass",
    id: 194556091,
    url: "https://soundcloud.com/rinos1337/sets/drum-and-bass",
    author: "rinos1337",
    author_link: "https://soundcloud.com/rinos1337",
  },
  {
    title: "Liquid Drum & Bass",
    id: 1158810049,
    url: "https://soundcloud.com/tom-lockwood-74750156/sets/liquicity-drum-bass",
    author: "Tom Lockwood",
    author_link: "https://soundcloud.com/tom-lockwood-74750156",
  },
  {
    title: "Vocal Drum & Bass",
    id: 1558629946,
    url: "https://soundcloud.com/ufiindia/sets/vocal-intelligent-liquid-drum",
    author: "UFI",
    author_link: "https://soundcloud.com/ufiindia",
  },
  {
    title: "Soulful Drum & Bass",
    id: 150768311,
    url: "https://soundcloud.com/liquidnb-ger/sets/intelligent-dnb",
    author: "LiquiDnB",
    author_link: "https://soundcloud.com/liquidnb-ger",
  },
  {
    title: "Deep Drum & Bass",
    id: 96576571,
    url: "https://soundcloud.com/lightningandthunder/sets/atmospheric-ambient-deep-dnb",
    author: "lightning and thunder",
    author_link: "https://soundcloud.com/lightningandthunder",
  },
  {
    title: "Dark Drum & Bass",
    id: 505897878,
    url: "https://soundcloud.com/user-189580618/sets/heavy-and-dark",
    author: "Slacky",
    author_link: "https://soundcloud.com/user-189580618",
  },
  {
    title: "Jungle & Breaks",
    id: 118780821,
    url: "https://soundcloud.com/solidbrasssam/sets/drum-and-bass-jungle",
    author: "solidbrasssam",
    author_link: "https://soundcloud.com/solidbrasssam",
  },
  {
    title: "NeuroFunk",
    id: 150766669,
    url: "https://soundcloud.com/liquidnb-ger/sets/hard-dnb",
    author: "LiquiDnB",
    author_link: "https://soundcloud.com/liquidnb-ger",
  },
  {
    title: "Techno",
    id: 288975225,
    url: "https://soundcloud.com/sazi-maqeda/sets/techno-1",
    author: "Sazi Maqeda",
    author_link: "https://soundcloud.com/sazi-maqeda",
  },
  {
    title: "Ambient Techno",
    id: 654156360,
    url: "https://soundcloud.com/quentin-bcs/sets/ambient-techno",
    author: "Quentin Bcs",
    author_link: "https://soundcloud.com/quentin-bcs",
  },
  {
    title: "Melodic Techno",
    id: 277782371,
    url: "https://soundcloud.com/redmar-zeehuisen/sets/melodic-techno",
    author: "Redmar",
    author_link: "https://soundcloud.com/redmar-zeehuisen",
  },
  {
    title: "Progressive Techno",
    id: 145555037,
    url: "https://soundcloud.com/justin-nauth/sets/atmospheric-and-progressive",
    author: "Justin Nauth",
    author_link: "https://soundcloud.com/justin-nauth",
  },
  {
    title: "Minimal",
    id: 1579088560,
    url: "https://soundcloud.com/thomas-fleming-01/sets/minimal-house-2-rekordbox",
    author: "Thomas Fleming",
    author_link: "https://soundcloud.com/thomas-fleming-01",
  },
  {
    title: "Lounge",
    id: 160355782,
    url: "https://soundcloud.com/chillyourmind/sets/cym",
    author: "ChillYourMind",
    author_link: "https://soundcloud.com/chillyourmind",
  },
  {
    title: "House",
    id: 322579795,
    url: "https://soundcloud.com/user-243181610/sets/deep-house",
    author: "H.Mastrogiannis",
    author_link: "https://soundcloud.com/user-243181610",
  },
  {
    title: "Chill House",
    id: 1598511478,
    url: "https://soundcloud.com/martin-heinrich-566502433/sets/vocal-chill-out-2023-chill",
    author: "DJ Eisb\xe6r",
    author_link: "https://soundcloud.com/martin-heinrich-566502433",
  },
  {
    title: "Minimal House",
    id: 837124259,
    url: "https://soundcloud.com/travel-instinct/sets/minimal-house",
    author: "m a k w z x",
    author_link: "https://soundcloud.com/travel-instinct",
  },
  {
    title: "Jazz House",
    id: 1545348502,
    url: "https://soundcloud.com/joseph-francisco-949977938/sets/funky-jazz-house-grooves-with",
    author: "Joseph Francisco",
    author_link: "https://soundcloud.com/joseph-francisco-949977938",
  },
  {
    title: "French House",
    id: 76871096,
    url: "https://soundcloud.com/nathan-lamb-1/sets/french-house-funk-tunes",
    author: "Nathan Lamb",
    author_link: "https://soundcloud.com/nathan-lamb-1",
  },
  {
    title: "Tropical House",
    id: 46568848,
    url: "https://soundcloud.com/iamwescos/sets/tropical-house",
    author: "Oscar Westman",
    author_link: "https://soundcloud.com/iamwescos",
  },
  {
    title: "Future House",
    id: 91523593,
    url: "https://soundcloud.com/ian-kaiser/sets/uk-garage",
    author: "Ian Kaiser",
    author_link: "https://soundcloud.com/ian-kaiser",
  },
  {
    title: "Progressive House",
    id: 185323829,
    url: "https://soundcloud.com/nola-kid/sets/progressive-house",
    author: "Nola Kid!",
    author_link: "https://soundcloud.com/nola-kid",
  },
  {
    title: "Deep House",
    id: 6126283,
    url: "https://soundcloud.com/deephousespace/sets/deep-house",
    author: "Deep House Space",
    author_link: "https://soundcloud.com/deephousespace",
  },
  {
    title: "Underground House",
    id: 198780487,
    url: "https://soundcloud.com/user-875116814/sets/underground-house",
    author: "Soundblaster",
    author_link: "https://soundcloud.com/user-875116814",
  },
  {
    title: "Progressive Trance",
    id: 18000023,
    url: "https://soundcloud.com/jpache/sets/progressive-trance",
    author: "jpache",
    author_link: "https://soundcloud.com/jpache",
  },
  {
    title: "Uplifting Trance",
    id: 17481898,
    url: "https://soundcloud.com/betawavemusic/sets/uplifting-trance",
    author: "BetaWave!",
    author_link: "https://soundcloud.com/betawavemusic",
  },
  {
    title: "Vocal Trance",
    id: 989457355,
    url: "https://soundcloud.com/niels-ketelaars-883054286/sets/vocal-trance",
    author: "Niels Ketelaars",
    author_link: "https://soundcloud.com/niels-ketelaars-883054286",
  },
  {
    title: "Psy Trance",
    id: 1186700950,
    url: "https://soundcloud.com/psydmr/sets/psychedelic-trance-1",
    author: "DMR PSYTRANCE",
    author_link: "https://soundcloud.com/psydmr",
  },
  {
    title: "Chillwave",
    id: 1438248220,
    url: "https://soundcloud.com/theociderecords/sets/chillwave-chill-synthwave",
    author: "Theocide Studios",
    author_link: "https://soundcloud.com/theociderecords",
  },
  {
    title: "Dreamwave",
    id: 689706285,
    url: "https://soundcloud.com/geoff_the_chef/sets/r-e-t-r-o-w-a-v-e",
    author: "C H E F G E O F F",
    author_link: "https://soundcloud.com/geoff_the_chef",
  },
  {
    title: "Vaporwave",
    id: 260939434,
    url: "https://soundcloud.com/eliud-makaveli-zavala/sets/vaporwave",
    author: "Eliud Makaveli Zavala",
    author_link: "https://soundcloud.com/eliud-makaveli-zavala",
  },
  {
    title: "Neowave",
    id: 229949598,
    url: "https://soundcloud.com/invdcgeymvhl/sets/retro-wave-synth-wave",
    author: "Jimmy",
    author_link: "https://soundcloud.com/invdcgeymvhl",
  },
  {
    title: "Synthwave",
    id: 358403271,
    url: "https://soundcloud.com/ferzrrn/sets/synthwave",
    author: "ferzrrn",
    author_link: "https://soundcloud.com/ferzrrn",
  },
  {
    title: "Hardwave",
    id: 1229701450,
    url: "https://soundcloud.com/japans/sets/hardwave",
    author: "c",
    author_link: "https://soundcloud.com/japans",
  },
  {
    title: "Darkwave",
    id: 296896590,
    url: "https://soundcloud.com/arctvria/sets/witch-house",
    author: "∆ЯCTVRI∆",
    author_link: "https://soundcloud.com/arctvria",
  },
  {
    title: "Thrillwave",
    id: 275152740,
    url: "https://soundcloud.com/heavyweightxl/sets/ambient-wave-trill-chill",
    author: "SYNDICVTE",
    author_link: "https://soundcloud.com/heavyweightxl",
  },
  {
    title: "Wave",
    id: 1278322258,
    url: "https://soundcloud.com/raffie-loiero/sets/wave",
    author: "Raffie Loiero",
    author_link: "https://soundcloud.com/raffie-loiero",
  },
];
